services:
  db:
    image: postgres:16
    container_name: messenger-pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: messenger
    ports:
      - "5433:5432"           
    volumes:
      - messenger_pg:/var/lib/postgresql/data
volumes:
  messenger_pg:
